package com.example.quezgame;

import java.util.ArrayList;

public class quezData {
    //171 questions

    String[] questions = {
            "Who is the Father of our Nation?",
            "Who was the first President of India?",
            "Who is known as the Father of the Indian Constitution?",
            "Which is the most sensitive organ in our body?",
            "Giddha is the folk dance of which state?",
            "Who was the first Prime Minister of India?",
            "Which is the heavier metal of these two? Gold or Silver?",
            "Who invented the computer?",
            "How many Kilobytes are equal to 1 Megabyte (MB)?",
            "Which component is known as the 'brain' of a computer?",

            "India lies in which continent?",
            "Which country are the Giza Pyramids in?",
            "What city is the Statue of Liberty in?",
            "How many Cricket World Cups does India have?",
            "Martyrs’ Day is celebrated every year on?",
            "Name the first 3 planets in our solar system?",
            "Which is the longest river on the Earth?",
            "Gir National Park in Gujarat is famous for?",
            "Which animal has a hump on its back?",
            "Name 1 root vegetable?",

            "Which game is played with bat, ball, and wicket?",
            "Which is the smallest state of India?",
            "What is the fastest animal on earth?",
            "Which animal is referred to as the 'ship of the desert'?",
            "Which plant typically grows in deserts?",
            "Which is the highest dam in India?",
            "The total distance around a figure is called its?",
            "A figure with 8 sides is called?",
            "Which color symbolizes peace?",
            "What is the national tree of India?",

            "Which flower is white in colour?",
            "Agra is situated on the bank of river?",
            "Baby of horse is called?",
            "National animal of India",
            "Shape of Egg is?",
            "Most widely spoken language in the world is?",
            "Which insect has colourful wings?",
            "Who wrote Romeo and Juliet?",
            "Cry of lion is called?",
            "Name any reptile?",
            "Cataract is the disease of?",
            "Which organ purifies our blood?",
            "Who wrote the National Anthem – Jana Gana Mana?",
            "How many colours are there in India's National Flag?",
            "Gateway of India is located at?",
            "Who was Albert Einstein?",
            "What crop is famously grown in the region of Darjeeling?",
            "Capital of Uttarakhand is?",
            "When do we celebrate our Independence Day?",
            "Sun is a?",

            "Which planet is nearest to Earth?",
            "We get solar energy from?",
            "What islands are a part of the country of India?",
            "Where does a dog live?",
            "Which animal is called the ship of the desert?",
            "Goitre is caused due to the deficiency of?",
            "Who was George Washington?",
            "Longest river in the world is?",
            "How many players are there in a cricket team?",
            "Largest island in the world is?",
            "Which president of the USA is responsible for the Emancipation Proclamation?",
            "LBW is related to which sports?",
            "Young one of a cat is called?",
            "Which African nation is famous for chocolate?",
            "Saina Nehwal is associated with which sports?",
            "How many days are there in a Leap year?",
            "Olympics games are held after every?",
            "How many sides are there in a pentagon?",
            "What is King Arthur’s sword called?",
            "A place where bees are kept is called?",
            "Which is the biggest sea animal?",
            "Who is the founder of Microsoft?",
            "Who discovered Penicillin?",
            "Who was popularly known as Netaji?",
            "Which country does the company Sony come from?",

            "What is the scientific study of birds called?",
            "Who is the author of the book 'Broken Wing'?",
            "Which is the largest desert in the world?",
            "In which direction does the sun rise?",
            "Kuchipudi is the dance form of which state?",
            "Who was Margaret Thatcher?",
            "On which day is United Nations (UN) Day celebrated?",
            "In which season do we wear warm clothes?",
            "Which bird cannot fly?",
            "When should we cross the road according to the traffic light?",
            "What is a place where animals and birds are kept called?",
            "In which festival do we play with colors?",
            "Which fruit gives us oil?",
            "Which jungle is the most dense in the world?",
            "What is the national song of India?",
            "What is the national bird of India?",
            "What is the national fruit of India?",
            "When is National Education Day celebrated?",
            "When is Children's Day celebrated?",
            "When is Teacher's Day celebrated?",
            "Which place is known as the tea garden of India?",
            "Which is the smallest bird?",
            "Which is the largest ocean in the world?",
            "Which is India's largest freshwater lake?",
            "Which is the tallest waterfall in the world?",

            "What does UPS stand for?",
            "Name the four metropolitan cities of India",
            "Name the birthplace of Netaji Subhash Chandra Bose",
            "What is the boiling point of water?",
            "Narendra Modi was the Chief Minister of which state?",
            "Which state has taken up Sanskrit as an official language?",
            "Name the first female Indian Astronaut",
            "Who was the first Indian to go to space?",
            "Who was India's longest serving Prime Minister?",
            "Which is the smallest continent?",
            "Who invented the telephone?",
            "Which acid is found in lemon?",
            "What is India's form of Governance?",
            "How many states does India have?",
            "Who was the first Indian Woman to climb Mount Everest?",
            "'Madhubani', a style of folk paintings, is popular in which of the following states in India?",
            "Australia lies between which two oceans?",
            "Name the 14th President of India",
            "Which Indian woman was the first to win the Nobel Prize?",
            "Who was the inventor of the light bulb?",
            "Who is the Finance Minister of India?",
            "What is the national game of USA?",
            "What is the full form of NEWS?",
            "What is the full form of AM and PM?",
            "Who is the Vice President of India?",
            "Name the lightest gas",
            "Who wrote Panchatantra?",
            "Who was the first Indian to have won the Nobel Prize?",
            "Name the region that has the oldest rocks",
            "Name the highest mountain peak of India",
            "Entomology is the science that studies",
            "How many layers are there in Earth's atmosphere?",
            "Name the biggest planet in our solar system",
            "Which is the largest plateau in the world?",
            "What is the order of the planets in the Solar System?",
            "Who invented the Television?",
            "Where are the Ajanta caves situated?",
            "What is the name of India and Pakistan's border?",
            "What is the ratio of width to the length of National Flag of India?",
            "Which gas is commonly known as laughing gas?",
            "Gandhi Ji started the Dandi March in which year?",
            "What is the study of the Universe known as?",
            "Why are the leaves of a plant so important?",
            "The famous Ganga Sagar Mela, an annual fair, is held in which state of India?",
            "Who is considered the founder of the Sikh religion?",
            "Who was known as the Indian Napoleon?",
            "Who gave the slogan 'Do or Die'?",
            "What is the distance between Earth and Sun?",
            "Which is the largest country in the world based on the area?",
            "What is the most spoken language in the world?",

            "Which is the largest bone in the human body?",
            "Which is the first biosphere reserve in India?",
            "Which is the largest freshwater lake in India?",
            "What is the full form of HTTP?",
            "Which planet is known as the Red Planet?",
            "Place these shapes in order of how many sides they have—square, triangle, octagon, and hexagon?",
            "Who discovered the theory of relativity?",
            "When is Hindi Diwas celebrated?",
            "What is the script for Hindi language?",
            "Who was the most sought-after social reformer after the end of Sati?",
            "What is the name of our galaxy?",
            "What is the percentage of water on the floor of our planet?",
            "When is Earth Day celebrated?",
            "Which is the longest river in India?",
            "Name the metals known to the people of Indus Valley Civilisation?",
            "Who was the first female Governor of an Indian State?",
            "Jhum cultivation is a method of cultivation which is used to be practised in which state?",
            "Which planet is the coldest planet in our solar system?",
            "Who was the first Muslim lady to rule the Delhi Throne?",
            "Where will you find the largest museum of India?",
            "Which is the shortest river in India?"
    };

    String[] optionA = {
            "Jawaharlal Nehru",
            "Dr.B.R. Ambedkar",
            "Mahatma Gandhi",
            "Eyes",
            "Gujarat",
            "Jawaharlal Nehru",
            "Gold",
            "Bill Gates",
            "512 Kilobytes",
            "CPU",
            "Europe",
            "Greece",
            "Los Angeles",
            "Two",
            "4th July",
            "Venus, Earth, Jupiter",
            "Amazon",
            "Elephant",
            "Horse",
            "Tomato",

            "Football",
            "Maharashtra",
            "Cheetah",
            "Horse",
            "Rose",
            "Bhakra Dam",
            "Diameter",
            "Hexagon",
            "Red",
            "Mango tree",

            "Rose",
            "Ganges",
            "Cub",
            "Tiger",
            "Square",
            "English",
            "Bee",
            "William Shakespeare",
            "Hiss",
            "Dolphin",
            "Heart",
            "Liver",
            "Rabindra Nath Tagore",
            "One",
            "Delhi",
            "Artist",
            "Wheat",
            "Dehradun",
            "26th January",
            "Planet",

            "Mars",
            "Wind",
            "Cocos Islands and Fiji Islands",
            "Stable",
            "Elephant",
            "Calcium",
            "Inventor of the telephone",
            "Amazon River",
            "9",
            "Borneo",
            "Abraham Lincoln",
            "Baseball",
            "Pup",
            "Ghana",
            "Tennis",
            "365",
            "2 years",
            "4",
            "Excalibur",
            "Stable",
            "Shark",
            "Steve Jobs",
            "Isaac Newton",
            "Mohandas Gandhi",
            "United States",

            "Entomology",
            "Sarojini Naidu",
            "Sahara Desert",
            "East",
            "Tamil Nadu",
            "Former President of the United States",
            "24th October",
            "Winter",
            "Eagle",
            "Red",
            "Park",
            "Diwali",
            "Banana",
            "Amazon Jungle",
            "Jana Gana Mana",
            "Peacock",
            "Mango",
            "15th August",
            "15th August",
            "15th August",
            "Darjeeling",
            "Penguin",
            "Atlantic Ocean",
            "Dal Lake",
            "Niagara Falls",

            "United Parcel Service",
            "Mumbai, Chennai, Kolkata, Delhi",
            "Cuttack in Odisha",
            "100 degrees Celsius",
            "Gujarat",
            "Uttarakhand",
            "Kalpana Chawla",
            "Rakesh Sharma",
            "Jawaharlal Nehru",
            "Australia",
            "Alexander Graham Bell",
            "Citric Acid",
            "Democracy",
            "29",
            "Bachendri Pal",
            "Bihar",
            "The Indian Ocean and Pacific Ocean",
            "Ram Nath Kovind",
            "Kalpana Chawla",
            "Thomas Edison",
            "Arun Jaitley",
            "Baseball",
            "Noteworthy Events Weather and Sports",
            "Ante Meridiem and After Midday",
            "Venkaiah Naidu",
            "Hydrogen",
            "Vishnu Sharma",
            "Rabindranath Tagore",
            "India",
            "Mount Kanchenjunga",
            "Insects",
            "5",
            "Jupiter",
            "Tibetan Plateau",
            "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune",
            "John Logie Baird",
            "Maharashtra",
            "Radcliffe Line",
            "2:3",
            "Nitrous oxide",
            "1930",
            "Cosmology",
            "They produce food for the plant through photosynthesis",
            "West Bengal",
            "Guru Nanak",
            "Samudragupta",
            "Mahatma Gandhi",
            "149.6 Million km",
            "Russia",
            "Mandarin or Chinese",

            "Femur",
            "Sunderbans Biosphere Reserve",
            "Dal Lake",
            "Hypertext Transfer Protocol",
            "Mars",
            "Square, Triangle, Octagon, Hexagon",
            "Isaac Newton",
            "September 14th",
            "Devanagari",
            "Raja Ram Mohan Roy",
            "Andromeda",
            "71 percent",
            "April 22nd",
            "Ganga",
            "Copper and Iron",
            "Sarojini Naidu",
            "Meghalaya",
            "Neptune",
            "Razia Sultan",
            "Mumbai",
            "Ganga"


    };

    String[] optionB = {
            "Mahatma Gandhi",
            "Jawaharlal Nehru",
            "Subhash Chandra Bose",
            "Ears",
            "Rajasthan",
            "Indira Gandhi",
            "Silver",
            "Steve Jobs",
            "1024 Kilobytes",
            "RAM",

            "Asia",
            "China",
            "New York City",
            "One",
            "30th January",
            "Mars, Eatth, Jupiter",
            "Nile",
            "Lion",
            "Camel",
            "Radish",

            "Cricket",
            "Kerala",
            "Lion",
            "Elephant",
            "Oak",
            "Sardar Sarovar Dam",
            "Perimeter",
            "Octagon",
            "Blue",
            "Banyan tree",

            "Lily",
            "Yamuna",
            "Fawn",
            "Lion",
            "Triangle",
            "Spanish",
            "Ant",
            "Jane Austen",
            "Roar",
            "Lizard",
            "Lungs",
            "Heart",
            "Mahatma Gandhi",
            "Two",
            "Kolkata",
            "Musician",
            "Rice",
            "Shimla",
            "1st May",
            "Moon",

            "Venus",
            "Water",
            "Andaman and Nicobar Islands",
            "Coop",
            "Horse",
            "Iodine",
            "First president of the United States of America",
            "Mississippi River",
            "10",
            "Greenland",
            "George Washington",
            "Soccer",
            "Kitten",
            "Kenya",
            "Badminton",
            "366",
            "3 years",
            "5",
            "Caliburn",
            "Coop",
            "Dolphin",
            "Mark Zuckerberg",
            "Alexander Fleming",
            "Jawaharlal Nehru",
            "Germany",

            "Ornithology",
            "Rabindranath Tagore",
            "Gobi Desert",
            "West",
            "Kerala",
            "Former Prime Minister of India",
            "1st January",
            "Spring",
            "Owl",
            "Yellow",
            "Zoo",
            "Christmas",
            "Orange",
            "Congo Jungle",
            "Vande Mataram",
            "Sparrow",
            "Apple",
            "26th January",
            "26th January",
            "26th January",
            "Ooty",
            "Sparrow",
            "Indian Ocean",
            "Wular Lake",
            "Victoria Falls",

            "Universal Power Source",
            "Delhi, Mumbai, Chennai, Jaipur",
            "Kolkata in West Bengal",
            "212 degrees Fahrenheit",
            "Rajasthan",
            "Himachal Pradesh",
            "Sunita Williams",
            "Vikram Sarabhai",
            "Indira Gandhi",
            "Asia",
            "Thomas Edison",
            "Sulfuric Acid",
            "Monarchy",
            "28",
            "Santosh Yadav",
            "Rajasthan",
            "The Atlantic Ocean and Indian Ocean",
            "Pranab Mukherjee",
            "Indira Gandhi",
            "Nikola Tesla",
            "Nirmala Sitharaman",
            "Basketball",
            "North East West South",
            "After Midnight and Post Morning",
            "Narendra Modi",
            "Helium",
            "Valmiki",
            "C. V. Raman",
            "Egypt",
            "Nanda Devi",
            "Birds",
            "4",
            "Saturn",
            "Colorado Plateau",
            "Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune",
            "Philipp Reis",
            "Karnataka",
            "Durand Line",
            "3:5",
            "Carbon dioxide",
            "1942",
            "Astrology",
            "They store water for the plant",
            "Uttar Pradesh",
            "Guru Gobind Singh",
            "Chandragupta Maurya",
            "Jawaharlal Nehru",
            "147.1 Million km",
            "Canada",
            "English",

            "Tibia",
            "Nanda Devi Biosphere Reserve",
            "Vembanad Lake",
            "Hypertext Transfer Program",
            "Venus",
            "Triangle, Square, Hexagon, Octagon",
            "Albert Einstein",
            "October 2nd",
            "Gurmukhi",
            "Jawaharlal Nehru",
            "Milky Way",
            "65 percent",
            "May 1st",
            "Yamuna",
            "Copper and Gold",
            "Indira Gandhi",
            "Assam",
            "Uranus",
            "Jodha Bai",
            "Delhi",
            "Yamuna"





            };

    String[] optionC = {
            "Subhash Chandra Bose",
            "Dr. Rajendra Prasad",
            "Dr.B.R. Ambedkar",
            "Nose",
            "Punjab",
            "Atal Bihari Vajpayee",
            "They have the same weight",
            "Alan Turing",
            "2048 Kilobytes",
            "GPU",

            "South America",
            "Egypt",
            "Washington D.C.",
            "Three",
            "25th December.",
            "Earth, Neptune, Uranus",
            "Mississippi",
            "Tiger",
            "Rhino",
            "Cucumber",

            "Tennis",
            "Goa",
            "Peregrine Falcon",
            "Camel",
            "Cactus",
            "Tehri Dam",
            "Circumference",
            "Pentagon",
            "Green",
            "Neem tree",

            "Sunflower",
            "Brahmaputra",
            "Calf",
            "Elephant",
            "Circle",
            "Mandarin (Chinese)",
            "Butterfly",
            "Charles Dickens",
            "Grunt",
            "Penguin",
            "Eyes",
            "Lungs",
            "Subhash Chandra Bose",
            "Three",
            "Mumbai",
            "Scientist",
            "Corn",
            "Jaipur",
            "15th August",
            "Star",

            "Jupiter",
            "Sun",
            "Canary Islands and Maldives",
            "Kennel",
            "Giraffe",
            "Iron",
            "Famous artist",
            "Nile River",
            "11",
            "Madagascar",
            "Thomas Jefferson",
            "Cricket",
            "Calf",
            "Nigeria",
            "Golf",
            "364",
            "4 years",
            "6",
            "Durandal",
            "Kennel",
            "Blue whale",
            "Bill Gates",
            "Albert Einstein",
            "Subhash Chandra Bose",
            "Japan",

            "Herpetology",
            "Arundhati Roy",
            "Kalahari Desert",
            "North",
            "Karnataka",
            "Former Prime Minister of the United Kingdom",
            "5th June",
            "Autumn",
            "Sparrow",
            "Green",
            "Garden",
            "Holi",
            "Coconut",
            "Borneo Jungle",
            "Saare Jahan Se Achcha",
            "Eagle",
            "Banana",
            "11th November",
            "14th November",
            "5th September",
            "Munnar",
            "Hummingbird",
            "Arctic Ocean",
            "Chilika Lake",
            "Angel Falls",

            "Uninterrupted Power Supply",
            "Kolkata, Delhi, Jaipur, Chennai",
            "Mumbai in Maharashtra",
            "0 degrees Celsius",
            "Uttar Pradesh",
            "Tamil Nadu",
            "Mamata Banerjee",
            "Yuri Gagarin",
            "Atal Bihari Vajpayee",
            "Africa",
            "Guglielmo Marconi",
            "Hydrochloric Acid",
            "Monarchy",
            "32",
            "Anshu Jamsenpa",
            "Uttar Pradesh",
            "The Pacific Ocean and Southern Ocean",
            "Pratibha Patil",
            "Sarojini Naidu",
            "Albert Einstein",
            "Piyush Goyal",
            "Football",
            "National Entertainment World Science",
            "Ante Meridian and Post Meridian",
            "Ram Nath Kovind",
            "Methane",
            "Tulsidas",
            "Har Gobind Khorana",
            "Arustralia",
            "Nanga Parbat",
            "Bacteria",
            "6",
            "Neptune",
            "Colorado Plateau",
            "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Pluto",
            "Philips",
            "Gujarat",
            "Indo-Pakistan Line",
            "2:4",
            "Oxygen",
            "1932",
            "Astronomy",
            "They release oxygen for us to breathe",
            "Haryana",
            "Guru Angad Dev",
            "Ashoka",
            "Subhash Chandra Bose",
            "152.1 Million km",
            "China",
            "Spanish",

            "Fibula",
            "Manas Biosphere Reserve",
            "Wular Lake",
            "Hyperspace Transfer Protocol",
            "Mercury",
            "Triangle, Square, Octagon, Hexagon",
            "Max Planck",
            "August 15th",
            "Bengali",
            "Veer Savarkar",
            "Black Hole",
            "85 percent",
            "June 5th",
            "Arvari",
            "Iron and Silver",
            "Vijayalakshmi Pandit",
            "Nagaland",
            "Pluto",
            "Razia Begum",
            "Kolkata",
            "Arvari"


    };

    String[] optionD = {
            "Sardar Vallabhbhai Patel",
            "Indira Gandhi",
            "Jawaharlal Nehru",
            "Skin",
            "Kerala",
            "Narendra Modi",
            "It depends on the quantity",
            "Charles Babbage",
            "4096 Kilobytes",
            "Hard Drive",

            "Africa",
            "Mexico",
            "Chicago",
            "Four",
            "1st May",
            "Mercury, Venus, Earth",
            "Yangtze",
            "Rhinoceros",
            "Bison",
            "Broccoli",

            "Basketball",
            "Uttar Pradesh",
            "Blue Whale",
            "Giraffe",
            "Maple",
            "Hirakud Dam",
            "Area",
            "Heptagon",
            "White",
            "Peepal tree",

            "Jasmine",
            "Indus",
            "Colt",
            "Peacock",
            "Oval",
            "Hindi",
            "Dragonfly",
            "Mark Twain",
            "Howl",
            "Koala",
            "Kidneys",
            "Kidney",
            "Jawaharlal Nehru",
            "Four",
            "Chennai",
            "Politician",
            "Tea leaves",
            "Lucknow",
            "2nd October",
            "Comet",

            "Mercury",
            "Moon",
            "Hawaii Islands and Seychelles Islands",
            "Hive",
            "Camel",
            "Vitamin C",
            "Legendary football player",
            "Yangtze River",
            "12",
            "Sumatra",
            "Franklin D. Roosevelt",
            "Basketball",
            "Foal",
            "South Africa",
            "Swimming",
            "363",
            "5 years",
            "7",
            "Joyeuse",
            "Hive",
            "Octopus",
            "Jeff Bezos",
            "Marie Curie",
            "Bhagat Singh",
            "South Korea",

            "Ichthyology",
            "Jhumpa Lahiri",
            "Atacama Desert",
            "South",
            "Andhra Pradesh",
            "Nobel laureate in literature",
            "31st December",
            "Summer",
            "Penguin",
            "Blue",
            "Sanctuary",
            "Easter",
            "Apple",
            "Sundarbans Jungle",
            "Vande Mataram",
            "Pigeon",
            "Grapes",
            "2nd October",
            "2nd October",
            "2nd October",
            "Nilgiri Hills",
            "Ostrich",
            "Pacific Ocean",
            "Vembanad Lake",
            "Iguazu Falls",

            "Universal Power Supply",
            "Mumbai, Delhi, Kolkata, Lucknow",
            "Chennai in Tamil Nadu",
            "32 degrees Fahrenheit",
            "Madhya Pradesh",
            "Kerala",
            "Kalpana Morparia",
            "Kalpana Chawla",
            "Manmohan Singh",
            "Europe",
            "Samuel Morse",
            "Acetic Acid",
            "Monarchy",
            "31",
            "Anita Kundu",
            "Uttarakhand",
            "The Arctic Ocean and Southern Ocean",
            "Pranab Mukherjee",
            "Mother Teresa",
            "Thomas Edison",
            "Piyush Goyal",
            "Soccer",
            "None of the above",
            "After Morning and Pre-Noon",
            "Jagdeep Dhankhar",
            "Helium",
            "Vishnu Sharma",
            "Rajendra Prasad",
            "Canada",
            "K2",
            "Fish",
            "7",
            "Mars",
            "Tibetan Plateau",
            "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Pluto",
            "David Sarnoff",
            "Madhya Pradesh",
            "McMahon Line",
            "3:2",
            "Methane",
            "1931",
            "Astrophysics",
            "They help in transpiration",
            "Rajasthan",
            "Guru Gobind Singh",
            "Akbar",
            "Vallabhbhai Patel",
            "149.6 Billion km",
            "USA",
            "Hindi",

            "Humerus",
            "Nilgiri Biosphere Reserve",
            "Loktak Lake",
            "Hyperspace Time Paradox",
            "Jupiter",
            "Octagon, Hexagon, Sauare, Triangle",
            "Nikola Tesla",
            "July 1st",
            "Tamil",
            "Bhagat Singh",
            "Saraswati",
            "97 percent",
            "March 8th",
            "Krishna",
            "Gold and Iron",
            "Sushma Swaraj",
            "Manipur",
            "Saturn",
            "Noor Jahan",
            "Chandigarh",
            "Krishana"
    };

    String[] correctAnswers = {
            "Mahatma Gandhi",
            "Dr. Rajendra Prasad",
            "Dr.B.R. Ambedkar",
            "Skin",
            "Punjab",
            "Jawaharlal Nehru",
            "Gold",
            "Charles Babbage",
            "1024 Kilobytes",
            "CPU",

            "Asia",
            "Egypt",
            "New York City",
            "Two",
            "30th January",
            "Mercury, Venus, Earth",
            "Nile",
            "Lion",
            "Camel",
            "Radish",

            "Cricket",
            "Goa",
            "Cheetah",
            "Camel",
            "Cactus",
            "Tehri Dam",
            "Perimeter",
            "Octagon",
            "White",
            "Banyan tree",

            "Jasmine",
            "Yamuna",
            "Colt",
            "Tiger",
            "Oval",
            "Mandarin (Chinese)",
            "Butterfly",
            "William Shakespeare",
            "Roar",
            "Lizard",
            "Eyes",
            "Kidney",
            "Rabindra Nath Tagore",
            "Three",
            "Mumbai",
            "Scientist",
            "Tea leaves",
            "Dehradun",
            "15th August",
            "Star",

            "Venus",
            "Sun",
            "Andaman and Nicobar Islands",
            "Kennel",
            "Camel",
            "Iodine",
            "First president of the United States of America",
            "Nile River",
            "11",
            "Greenland",
            "Abraham Lincoln",
            "Cricket",
            "Kitten",
            "Ghana",
            "Badminton",
            "366",
            "4 years",
            "5",
            "Excalibur",
            "Hive",
            "Blue whale",
            "Bill Gates",
            "Alexander Fleming",
            "Subhash Chandra Bose",
            "Japan",

            "Ornithology",
            "Sarojini Naidu",
            "Sahara Desert",
            "East",
            "Andhra Pradesh",
            "Former Prime Minister of the United Kingdom",
            "24th October",
            "Winter",
            "Penguin",
            "Green",
            "Zoo",
            "Holi",
            "Coconut",
            "Amazon Jungle",
            "Vande Mataram",
            "Peacock",
            "Mango",
            "11th November",
            "14th November",
            "5th September",
            "Darjeeling",
            "Hummingbird",
            "Pacific Ocean",
            "Wular Lake",
            "Angel Falls",

            "Uninterrupted Power Supply",
            "Mumbai, Chennai, Kolkata, Delhi",
            "Cuttack in Odisha",
            "100 degrees Celsius",
            "Gujarat",
            "Uttarakhand",
            "Kalpana Chawla",
            "Rakesh Sharma",
            "Jawaharlal Nehru",
            "Australia",
            "Alexander Graham Bell",
            "Citric Acid",
            "Democracy",
            "28",
            "Bachendri Pal",
            "Bihar",
            "The Indian Ocean and Pacific Ocean",
            "Ram Nath Kovind",
            "Mother Teresa",
            "Thomas Edison",
            "Nirmala Sitharaman",
            "Baseball",
            "North East West South",
            "Ante Meridian and Post Meridian",
            "Jagdeep Dhankhar",
            "Hydrogen",
            "Vishnu Sharma",
            "Rabindranath Tagore",
            "Canada",
            "Mount Kanchenjunga",
            "Insect",
            "5",
            "Jupiter",
            "Tibetan Plateau",
            "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune",
            "John Logie Baird",
            "Maharashtra",
            "Radcliffe Line",
            "2:3",
            "Nitrous oxide",
            "1930",
            "Cosmology",
            "They produce food for the plant through photosynthesis",
            "West Bengal",
            "Guru Nanak",
            "Samudragupta",
            "Mahatma Gandhi",
            "152.1 Million km",
            "Russia",
            "Mandarin or Chinese",

            "Femur",
            "Nilgiri Biosphere Reserve",
            "Wular Lake",
            "Hypertext Transfer Protocol",
            "Mars",
            "Triangle, Square, Hexagon, Octagon",
            "Albert Einstein",
            "September 14th",
            "Devanagari",
            "Raja Ram Mohan Roy",
            "Milky Way",
            "71 percent",
            "April 22nd",
            "Ganga",
            "Copper and Gold",
            "Sarojini Naidu",
            "Nagaland",
            "Uranus",
            "Razia Sultan",
            "Kolkata",
            "Arvari"
    };


}
